### ISSUE TITLE
toDecimalString not showing enough decimals

### ISSUE THREAD

**Issue by pablokrupa** [rwpenney/spfpm#11]
The following code
```
from FixedPoint import FXfamily, FXnum
fam2 = FXfamily(2)
z = FXnum(1.25, fam2)
print(z.toDecimalString())
print(z.toBinaryString())
```
prints
```
1.2
1.01
```
The binary value (1.01) is clearly correct and correctly printed. However, the decimal value printed is 1.2, when I believe the desired result would be for it to print 1.25 if no precision is set in the toDecimalString() method.

The string 1.25 is printed if `print(z.toDecimalString(2))` is used (or any number >2).

I believe the issue comes from how precision is set in toDecimalString() in the default case. See line 487 of FixedPoint.py (commit [c067b92](https://github.com/rwpenney/spfpm/commit/c067b92302dee972a3644365920c4ebc2b29076b)). It is not large enough for the case of a fractional precision of 2. I have not tested it with other values of the fractional precision.

**Comment by rwpenney** [comment]
Thanks, @pablokrupa , for flagging this. The `toDecimalString()` method continues to be an awkward compromise between trying to represent the *maximum possible* precision of an `FXnum` and the *sensibly realistic* precision one might obtain from a computation.

Basic integer-divisibility arguments show that a b-bit fractional number will also need b decimal digits to be completely represented in base-10. However, if we consider an `FXfamily(8)`, then the *useful* precision with which we can do most calculations is only about 0.004, which is much less than 8 digits of decimal precision. When using much larger numbers of fractional digits, we'd over-represent the effective number of reliable digits by a factor of about 1/log10(2), or about 3.3.

I've [now reworked](https://github.com/rwpenney/spfpm/commit/2238318bb7b081664613a5d46ba08c22002280f9) the `toDecimal()` method so that it uses a better heuristic so that very narrow `FXnum`s have the "optimistic" number of decimal digits, but it rapidly asymptotes towards about 0.3 extra decimal digits per bit. The documentation also makes clear that the `precision` argument can be used overrule the default behaviour.

I hope this is useful step forward.

**Comment by pablokrupa** [comment]
Fantastic! Thanks for the explanation and the rework. I will close this issue.
