### ISSUE TITLE
Mismatched Families Exception

### ISSUE THREAD

**Issue by wittmarf** [rwpenney/spfpm#2]
Hello,

I found this problem in your very nice library:

a  =  FXnum(1.2, FXfamily(8))
b  =  FXnum(1.8, FXfamily(8))
c = a*b                                           # throws exception!

But if you write it like this, it works:

fam = FXfamily(8)
a  =  FXnum(1.2, fam)
b  =  FXnum(1.8, fam)
c = a*b                                           

Thank you and Greetings,
Ralf

**Comment by rwpenney** [comment]
Hello Ralf,
Thanks for your email - I'm glad to hear that you're finding spfpm of
some use.

The exception you're seeing is the result of a (possibly questionable)
design choice. This was intended to maximize the speed with which
arithmetic operations could check whether two FXnum objects were from
a compatible FXfamily, and allow users to provide some means of
partitioning related fixed-point numbers according to their resolution.
This means that internally, I'd chosen to compare the FXfamily of two
FXnums by checking that they refer to the same object, rather than that
they are logically equivalent.

Having run some quick tests with Python-3.4, although there seems to be
a detectable benefit to the current implementation rather than
comparing two FXfamily objects for equivalence, the benefit is quite
small.

I'll do some more careful experiments to check whether it would make
more sense to change the way FXnums check that they refer to equivalent
FXfamilies. I suspect there will be an updated version of SPFPM soon...

	Kind regards,
		Richard

**Comment by wittmarf** [comment]
Dear Richard,

I am glad you wrote spfpm and saved me the work! Python has fixed point
arithmetic only for decimals, not for binary numbers. But hardware is
binary, of course.

Once the user is aware of the way spfpm checks for equality, your
implementation is no problem at all. In my case, I was not sure if I had
some misconceptions about fixed point numbers before I found the cause of
the exceptions.

I am using your library for the simulation of neural networks. Common
software for machine learning (like Tensorflow) works with 32 bit floats,
which is not suited for FPGA applications. I was able to use 16 bit fixed
point instead - and even less. Typically you have up to 5000
multiplications followed by adding the results (MAC). Ideally one would
choose 8 bit inputs, because then one multiplier can be used for two
multiplications in parallel - saving time and energy. This aprearently
works, but the hard part is to round the result back to 8 bit for the next
MAC process. In general this is hopeless, but with neural networks one of
the two inputs (the weights) is roughly Gauss distributed around zero. So
"rounding" boils down to finding a good scaling factor (and possibly an
offset value).

Yours sincerly,
Ralf Wittmann

2017-05-05 18:28 GMT+02:00 Richard Penney <notifications@github.com>:
