### ISSUE TITLE
0**x returns unity

### ISSUE THREAD

**Issue by KristofferDerosche** [rwpenney/spfpm#9]
I do believe this is an error and can be fixed by changing line 561

return self.family.unity -> return self.family.zero

I dont know if this will result in any unforeseen issues.

**Comment by rwpenney** [comment]
Thanks, Kristoffer, for catching this silly error of mine.
I've (hopefully) improved the handling of 0^x for both the case where x>0 and also x<=0 which now throws an exception. The unit-tests should also be a bit more robust.
The fix is in commit bd1407a0db16c6f8994d194fd3c385b34f7eaec4, version 1.4.7.
